const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
module.exports = {
    mode: 'development',
    devServer: {
        port: 8082
    },
    plugins:[
        new ModuleFederationPlugin({
            name:'cart', //how to ref in other projects
            filename:'remoteEntry.js',  // generated by MFP, list of files available from project and loading instructions
            exposes:{'./CartShow':'./src/index'}, // defines what files/modules will be exposed, key is an alias for file path
            shared: ['faker'] // shared dependency, will be loaded by webpack only once if same version
        }),
        new HtmlWebpackPlugin({
        template: './public/index.html'
    }),
    ]
}