const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
module.exports = {
    mode: 'development',
    devServer: {
        port: 8081
    },
    plugins: [
        new ModuleFederationPlugin({
            name: 'products', //how to ref in other projects
            filename: 'remoteEntry.js',  // generated by MFP, list of files available from project and loading instructions
            exposes: {'./ProductsIndex': './src/index'}, // defines what files/modules will be exposed, key is an alias for file path
            shared: ['faker'] // shared dependency, will be loaded by webpack only once
        }),
        new HtmlWebpackPlugin({
            template: './public/index.html'
        }),
    ]
}